### PR TITLE
[WIP] Adding a custom Uri-Handler for pretixdroid-events

### PR DESCRIPTION
**Pull request by jfwiebe**
I added an intent-handler for Uris of the scheme "pretixdroid://[eventconfig]" where [eventconfig] stands for the base64-encoded json object encoded in the configuration barcode. A link can e.g. look like this:
`pretixdroid://eyJrZXkiOiAiSklmbTFiOWZNaGxLQkl4UmFSdHNJYnJlbDN2OWFHTHgiLCAidXJsIjogImh0dHBzOi8vdGlja2V0cy5qZndpZS5iZS9wcmV0aXhkcm9pZC9hcGkvazQvdGVzdC8iLCAidmVyc2lvbiI6IDJ9`

This PR ist still work in progress. For example, when changing display orientation, the onCreate-method is called again and the configuration will be shown again.

### CODE REVIEW

**Comment by raphaelm** [comment]
Interesting idea. I'm a bit torn apart here, as it seems like a very useful thing to have if you open pretix on your smartphone and want to open pretixdroid on the same device, but it also could make people send those links over insecure channels which makes them less protected than the QR-code method. I need to think about this shortly, but I think we can merge it and try to design the web UI in a way that does not make it obvious that this is a shareable link.

**Comment by raphaelm** [comment]
It is unclear to me why the travis build fails (it exits with "Killed")...

**Comment by raphaelm** [comment]
Ok, I'm gonna merge this for now. Do you want to include the link into the pretix interface or should I?

**Comment by raphaelm** [comment]
Uhm, sorry for my comment spam. Didn't reed the onCreate part in your message. That should probably  be fixed before a merge.

**Comment by jfwiebe** [comment]
@raphaelm thanks for your feedback. Maybe the build failed because of this commit: https://github.com/pretix/pretixdroid/pull/9/commits/34a9aeb58696ef5ef20da153fb7f205599a2705f 

In the end, I did not even used the java8 expressions here so I think I will revert it and try if it builds again.

**Comment by jfwiebe** [comment]
@raphaelm I share your thoughts about sharing the "insecure" channel. But the qr-code is not better. A user can save the image and then share it via $messenger.

To address this, we need a different way of handling out the secure channel between phone and plugin. Maybe you should have a look at the "Whatsapp Web" implementation. They are using a "pairing" key which becomes invalid after a few minutes. If the user scans the pairing key with their phone, this key will be used to negotiate (or just recieve?) a communication key which is bound to that device. The pairing key will be marked as used and no communication key will be issued for that paring key again. With that architecture, each qr code becomes invalid after x seconds and if someone used it for pairing.

**Comment by raphaelm** [comment]
It's not that easy to save our current QR code as an image, actually (although it is not originally intended to be hard). I think the QR code is a pretty okay solution for now as it makes the configuration very easy and straightforward, especially with multiple devices, but in the future we could think about a more sophisticated solution like that, yes.

**Comment by jfwiebe** [comment]
I originally thought about creating a screenshot which is pretty easy in my eyes. For example, for one event for that I hosted pretix, I printed out the QR-Code and sticked into the office so that every volunteer was able to scan the code and start scanning tickets.

But you are right, this is a totally different topic.

**Comment by raphaelm** [comment]
> I originally thought about creating a screenshot which is pretty easy in my eyes.

Yes, of course. Not for everyone, though.

> For example, for one event for that I hosted pretix, I printed out the QR-Code and sticked into the office so that every volunteer was able to scan the code and start scanning tickets.

…which is very useful and convenient and not possible using single-use keys. I see the pros and cons, but I think the current solution is not that bad.

**Comment by jfwiebe** [comment]
Hi. I implemented a small if statement to check if there is already a configuration with the same key but right after pushing, I think it maybe has made it even worse. There is a second code which parses the JSON and there are still use cases which lead into strage behavior: clicking a link, (config is not loaded), user selects "reset config", user turns the screen, it shows "config successfully scanned".

I really do not know how to do. Every messenger handles intents correctly and I do not know how.

**Comment by raphaelm** [comment]
Hi Jan Felix, no worries! The activity lifecycle is a very nasty and annoying thing. If you turn your device, ``onCreate()`` is called again and thus your logic runs again. In a different app that I maintain we apparently do it like this:

```
        if (getIntent() != null && getIntent().getAction() != null) {
            if (getIntent().getAction().equals("android.intent.action.VIEW")) {
                // Handle the intent
```

So I think this here is still doable (but I feel #4 is of much more value :wink:)

**Comment by jfwiebe** [comment]
Hi,

thanks for your feedback! I wanted to implement this small idea fast but now it was sitting around for so long, very anoying - #4 is the thing for me to do now ;)

Greetings, Jan Felix

 

Von: Raphael Michel [mailto:notifications@github.com] 
Gesendet: Donnerstag, 30. März 2017 13:25
An: pretix/pretixdroid <pretixdroid@noreply.github.com>
Cc: Jan Felix Wiebe <mail@jfwie.be>; State change <state_change@noreply.github.com>
Betreff: Re: [pretix/pretixdroid] [WIP] Adding a custom Uri-Handler for pretixdroid-events (#9)

 

Hi Jan Felix, no worries! The activity lifecycle is a very nasty and annoying thing. If you turn your device, onCreate() is called again and thus your logic runs again. In a different app that I maintain we apparently do it like this:

        if (getIntent() != null && getIntent().getAction() != null) {
            if (getIntent().getAction().equals("android.intent.action.VIEW")) {
                // Handle the intent

So I think this here is still doable (but I feel #4 <https://github.com/pretix/pretixdroid/issues/4>  is of much more value 😉)

**Pull request closed without merging**
