### PR TITLE
Fix F-Droid Badge

### PR DESCRIPTION
**Pull request by EvangelinePetersen**

### CODE REVIEW

**Comment by johan12345** [comment]
Hi, the old link https://f-droid.org/badge/get-it-on.png still seems to work. Why do we need to change the URL?

**Comment by EvangelinePetersen** [comment]
I do not see the badge in the readme. Please see the attached screenshot. In my browser, [https://f-droid.org/badge/get-it-on.png](https://f-droid.org/badge/get-it-on.png) redirects to [https://fdroid.gitlab.io/artwork/badge/get-it-on.png](https://fdroid.gitlab.io/artwork/badge/get-it-on.png).
Is that a problem on my side?
fdroidbadge

P.S. Instead of loading the badge from an external page, we might use it from [https://user-images.githubusercontent.com/42723388/47257291-3422b580-d48c-11e8-8fa2-6c434ea68a1f.png](https://user-images.githubusercontent.com/42723388/47257291-3422b580-d48c-11e8-8fa2-6c434ea68a1f.png) instead. So please tell me what you prefer in case that the badge does not appear in the readme in your browser too.

**Comment by johan12345** [comment]
Ah, right, now it doesn't show for me either - strange that it worked earlier...

**Comment by johan12345** [comment]
@raphaelm, should be good to merge.

**Comment by EvangelinePetersen** [comment]
In the meantime, the F-Droid badge showed up for me one time too. But not constantly. Most of the time it is away. Very mysterious... 👻

I changed the badges in the last commit so that it gets the badges from GitHub directly.
Maybe that is the safest way? 🤔
Additionally, Google, F-Droid & GitLab cannot track how often your repo is accessed that way.

**Pull request merged**
